"""
Build prototype/tree-anatomy.js from the four mood images.

Runs branch detection on each tree image and emits a browser-loadable JS
file (works from file:// — no fetch needed) exposing:

  window.TREE_ANATOMY = {
    imageWidth, imageHeight,
    moods: { peaceful: {image, slots:[{x,y,angle,kind}]}, ... }
  }

Re-run whenever a tree image is replaced:
  python3 tools/build_anatomy.py
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from detect_branches import detect
from tree_body import tree_body
import base64
import numpy as np
from scipy import ndimage as ndi
from skimage import morphology

CELL = 4   # clearance field resolution (px per cell)

ROOT = os.path.join(os.path.dirname(__file__), '..', 'prototype')
MOODS = ['peaceful', 'unsettled', 'stormy', 'eerie']

out = {'moods': {}}
for m in MOODS:
    r = detect(os.path.join(ROOT, 'assets', f'tree-{m}.png'))
    r.pop('debug', None)
    out['imageWidth'], out['imageHeight'] = r['width'], r['height']
    slots = r['tips'] + r['twigSlots']
    # Tree body = connected trunk/limb mask ∪ the twigs the detector found
    body = tree_body(os.path.join(ROOT, 'assets', f'tree-{m}.png'))
    body |= morphology.dilation(r.pop('_twig_mask'), morphology.disk(2))
    # Close only small pits in the bark — NOT the sky pockets enclosed
    # between branches (fill_holes would turn that open air into 'tree').
    body = morphology.remove_small_holes(body, area_threshold=900)
    # Clearance: px distance to the nearest tree pixel. Down-sampled
    # CONSERVATIVELY (min over each cell) so the browser never over-estimates.
    dist = ndi.distance_transform_edt(~body)

    # Edge shoots: leaves may also sprout from the OUTER EDGE of limbs.
    # Sample the body boundary inside the canopy (not the trunk), each with
    # its outward normal so the leaf grows into open air.
    Hh, Ww = body.shape
    edge = body & ~ndi.binary_erosion(body)
    yy, xx = np.nonzero(edge)
    gy, gx = np.gradient(dist)
    keep_pts, taken = [], []
    order = np.random.default_rng(13).permutation(len(yy))
    for k in order:
        y, x = int(yy[k]), int(xx[k])
        if y > Hh * 0.56: continue
        if abs(x - Ww / 2) < Ww * 0.09 and y > Hh * 0.18: continue      # trunk: no leaves
        if any((x - a) ** 2 + (y - b) ** 2 < 81 for a, b in taken[-400:]): continue
        # outward normal = gradient of distance just outside the boundary
        y1, x1 = min(Hh - 1, y + 1), min(Ww - 1, x + 1)
        nx, ny = gx[y, x] + gx[y1, x1], gy[y, x] + gy[y1, x1]
        if nx == 0 and ny == 0: continue
        ang = float(np.degrees(np.arctan2(-ny, nx)))
        keep_pts.append({'x': round(x / Ww, 4), 'y': round(y / Hh, 4), 'angle': round(ang, 1), 'kind': 'edge'})
        taken.append((x, y))
    slots = slots + keep_pts
    H, W = dist.shape
    h4, w4 = H // CELL, W // CELL
    d4 = dist[:h4 * CELL, :w4 * CELL].reshape(h4, CELL, w4, CELL).min(axis=(1, 3))
    q = np.clip(np.floor(d4), 0, 255).astype(np.uint8)

    # Medial axis of the tree body at field resolution: sap runs ONLY along it,
    # so the vascular network is a single branching tree (no parallel cables).
    body4 = (q == 0)
    axis = morphology.skeletonize(body4)
    axis_bits = np.packbits(axis.astype(np.uint8).ravel())
    out['moods'][m] = {'image': f'./assets/tree-{m}.png', 'slots': slots,
                       'clearance': {'cell': CELL, 'w': w4, 'h': h4,
                                     'data': base64.b64encode(q.tobytes()).decode(),
                                     'axis': base64.b64encode(axis_bits.tobytes()).decode()}}
    print(f'{m}: {len(r["tips"])} tips + {len(r["twigSlots"])} twig slots + {len(slots) - len(r["tips"]) - len(r["twigSlots"])} edge shoots')

js = ('/* AUTO-GENERATED by tools/build_anatomy.py — do not edit by hand. */\n'
      'window.TREE_ANATOMY = ' + json.dumps(out, separators=(',', ':')) + ';\n')
with open(os.path.join(ROOT, 'tree-anatomy.js'), 'w') as f:
    f.write(js)
print('wrote prototype/tree-anatomy.js', len(js), 'bytes')
